import Head from 'next/head'
import {Box} from "@mui/system";
import About from "../src/components/About/About";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Biz haqimizda.</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Box>
                <About />
            </Box>
        </div>
    )
}
