import Head from 'next/head'
import {Box} from "@mui/system";
import SingleServices from "../src/components/SingleService/SingleService";
import {useContext} from "react";
import CreateContextApi from "../src/context/createContext";

export default function Home() {
    const ctxSetValue = useContext(CreateContextApi);
    const {services} = ctxSetValue;
    // @ts-ignore
    const title = services[0];
    return (
        <div>
            <Head>
                <title>{title.name}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Box>
                <SingleServices data={services}/>
            </Box>
        </div>
    )
}
